### ISSUE TITLE
Stylesheet reference gives 404

### ISSUE THREAD

**Issue by ciacciojon9999** [ufclas/UF-CLAS-DEPT#4]
Theme references stylesheet directly. File is also 403 forbidden https://cloud.typography.com/6019574/7283992/css/fonts.css
a.	Use https://developer.wordpress.org/themes/basics/including-css-javascript/

**Comment by clascomm** [comment]
I've sent the new font files (Hoefler generates these) to you and Brent to upload to the test.clas.ufl.edu/fonts folder.
